name: C/C++ CI

on:
  watch:
    types: [started]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make tools check
      run: make tools check

